name: Build & Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]



jobs:
  prepare-laravel:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@b7d1d9c9a92d8d8463ce36d7f60da34d461724f8
      with:
        php-version: '8.0'
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
      
  run-tests:
    needs : [prepare-laravel]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: vendor/bin/phpunit
        
  build-assets:
      needs : [prepare-laravel, run-tests]
      runs-on: ubuntu-latest
      
      steps:
        - name: Use Node.js
          uses: actions/setup-node@v1
          with:
            node-version: 14.16.1
        - name: Checkout repo
          uses: actions/checkout@v2
        - name: Install deps
          run: yarn
        - name: Build deps
          run: yarn production
          
  forge-deploy:
    needs : [prepare-laravel, run-tests, build-assets]
    runs-on: ubuntu-latest

    steps:
    - name: deploy to forge
      uses: fjogeleit/http-request-action@v1.8.0
      with: 
        url: ${{ secrets.DEPLOY_URL }}
            
      



